# Generated by Django 4.0.4 on 2022-05-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_totalbook_order_totalcake_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Cake',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='cake',
        ),
    ]
