# Generated by Django 4.0.4 on 2022-05-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalbook',
            new_name='totalCake',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='book',
            new_name='cake',
        ),
    ]
